### ISSUE TITLE
KODEN IPTV TR eklentisi yüklenmiyor.

### ISSUE THREAD

**Issue by optimumbroccoli** [ubden/kodentv#10]
Her zaman kullandığım Haydaa TV kanallarına erişemiyorum. KODEN IPTV TR eklentisi yüklenmiyor. Bağımlılıkları manuel olarak kurdum ama yine de yüklenmiyor.

**Comment by ubden** [comment]
Sorunu şablona uygun şekilde tekrar gönderin.
