### ISSUE TITLE
kurulum sihirbazı hatası

### ISSUE THREAD

**Issue by mhvei65** [ubden/kodentv#11]
merhaba, kurulum videosundaki adımları harfiyen yerine getirmeme rağmen kodentv'nin program eklentisi kurulurken indirme tamamlanıyor lakin kurarken hata alıyorum. internetten yana sıkıntı yok. pc de sağlam. işlemleri tekrar başa alıyorum ama nafile. Android telefondan yapayım diyorum orada da aynı hata. internet kaynağını değiştiriyorum yine aynı hata. Lüten yardım edin.

**Comment by ubden** [comment]
Sorunu şablona uygun şekilde tekrar gönderin.
